from . import alrightness_pricess
from . import calculator_tool
from . import commission_point
from . import commission_table
from . import coring_coster
from . import coring_coster_line
from . import dwelling_ventilation
from . import floor_names
from . import placement_config
from . import postal_code
from . import room_measurement
from . import sale_order_prod_line
from . import shipping_cost
from . import inh_prod_category
from . import inh_prod_prod
from . import inh_prod_temp
from . import inh_res_country
from . import inh_res_country_state
from . import inh_res_partner
from . import inh_sale_order
from . import inh_sale_order_line
from . import inh_stock_rule
from . import cron_job